name: my CI CD Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build-and-deploy:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies    
      run: npm install
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm run test:unit
    - name: Deploy to GitHub Pages
      id: deployment
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
          token: ${{ secrets.ACCESS_TOKEN }} # Settings > Secret 建立的 ACCESS_TOKEN，推同個 repo 的話可以不需要
          BRANCH: gh-pages # deploy 到 gh-pages 這個分支
          FOLDER: dist # build 後的資料夾
      
